//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNC12.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HienTrangCuaMayCNC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HienTrangCuaMayCNC()
        {
            this.EventManagerCNC1 = new HashSet<EventManagerCNC1>();
            this.EventManagerCNC2 = new HashSet<EventManagerCNC2>();
            this.EventManagerCNC3 = new HashSet<EventManagerCNC3>();
            this.EventManagerCNC4 = new HashSet<EventManagerCNC4>();
            this.EventManagerCNC5 = new HashSet<EventManagerCNC5>();
            this.EventManagerCNC6 = new HashSet<EventManagerCNC6>();
            this.EventManagerCNC7 = new HashSet<EventManagerCNC7>();
            this.EventManagerCNC8 = new HashSet<EventManagerCNC8>();
        }
    
        public int Id { get; set; }
        public string DisplayName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventManagerCNC1> EventManagerCNC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventManagerCNC2> EventManagerCNC2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventManagerCNC3> EventManagerCNC3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventManagerCNC4> EventManagerCNC4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventManagerCNC5> EventManagerCNC5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventManagerCNC6> EventManagerCNC6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventManagerCNC7> EventManagerCNC7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventManagerCNC8> EventManagerCNC8 { get; set; }
    }
}
