//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNC12.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineStatu
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public int IdCaLamViec { get; set; }
        public int IdChucVu { get; set; }
        public int StatusOnl { get; set; }
        public Nullable<System.DateTime> ThoiDiem { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual ChucVu ChucVu1 { get; set; }
    }
}
